# Generated by Django 5.0.6 on 2024-05-15 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Семейство')),
                ('continent', models.CharField(max_length=20, verbose_name='Континент')),
            ],
            options={
                'verbose_name': 'Семейство',
                'verbose_name_plural': 'Семейства',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Страна')),
                ('climat', models.CharField(max_length=25, verbose_name='Климат')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Корм',
                'verbose_name_plural': 'Корма',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Промокод')),
                ('percentage', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('daily_norm', models.PositiveIntegerField(verbose_name='Дневная норма')),
                ('date_of_receipt', models.DateField(verbose_name='Дата поступления')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('feeding_schedule', models.CharField(max_length=60, verbose_name='График кормления')),
                ('image', models.ImageField(default='images/no.jpg', upload_to='images/', verbose_name='Фото животного')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Сотрудник')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoopark.animalfamily', verbose_name='Семейство')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoopark.animaltype', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Aviary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('number', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь')),
                ('reservoir', models.BooleanField(verbose_name='Водоем')),
                ('heating', models.BooleanField(verbose_name='Отопление')),
                ('countOfAnimals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_of_animal', to='zoopark.animal')),
            ],
            options={
                'verbose_name': 'Вольер',
                'verbose_name_plural': 'Вольеры',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='aviary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoopark.aviary', verbose_name='Вольер'),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoopark.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='animal',
            name='feed',
            field=models.ManyToManyField(to='zoopark.feed', verbose_name='Корм'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('excursion', models.BooleanField(verbose_name='Экскурсия')),
                ('feeding', models.BooleanField(verbose_name='Кормление')),
                ('photosession', models.BooleanField(verbose_name='Фотосессия')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoopark.promocode', verbose_name='Промокод')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
