# Generated by Django 5.0.6 on 2024-05-16 14:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0002_remove_aviary_countofanimals_remove_aviary_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 16))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 5, 16))], verbose_name='Дата поступления'),
        ),
    ]
