# Generated by Django 5.0.6 on 2024-09-05 14:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0003_alter_animal_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Адрес')),
                ('image', models.ImageField(default='images/zoopark_icon.jpg', upload_to='images/', verbose_name='Логотип')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 5))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 5))], verbose_name='Дата поступления'),
        ),
    ]
