# Generated by Django 5.0.6 on 2024-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0004_partner_alter_animal_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=150, verbose_name='Описание')),
                ('history', models.CharField(max_length=250, verbose_name='История')),
                ('certificate', models.CharField(max_length=250, verbose_name='Сертификат')),
                ('requisites', models.CharField(max_length=50, verbose_name='Реквизиты')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('image', models.ImageField(default='images/zoopark_icon.jpg', upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
