# Generated by Django 5.0.6 on 2024-09-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
