# Generated by Django 5.0.6 on 2024-09-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_position_description'),
        ('zoopark', '0009_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.position', verbose_name='Должность')),
            ],
        ),
    ]
