# Generated by Django 5.0.4 on 2024-09-26 18:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0012_ticket_count_ticket_paid_alter_animal_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name_lower',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя в нижнем регистре'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 26))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 26))], verbose_name='Дата поступления'),
        ),
    ]
