# Generated by Django 5.0.4 on 2024-09-30 19:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0015_remove_feedback_user_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(default=1000, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 30))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 30))], verbose_name='Дата поступления'),
        ),
    ]
