# Generated by Django 5.0.4 on 2024-10-01 15:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0018_promocode_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(default=datetime.date(2024, 10, 1), verbose_name='Дата')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('text', models.CharField(max_length=600, verbose_name='Текст')),
                ('background_image', models.ImageField(default='images/white_background.png', upload_to='images/', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 1))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 1))], verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='company',
            name='certificate',
            field=models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.SET_DEFAULT, to='zoopark.certificate', verbose_name='Сертификат'),
        ),
    ]
