# Generated by Django 5.0.4 on 2024-10-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0020_alter_company_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='certificate',
        ),
    ]
