# Generated by Django 5.0.4 on 2024-10-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0022_company_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
