# Generated by Django 5.0.6 on 2024-05-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviary',
            name='countOfAnimals',
        ),
        migrations.RemoveField(
            model_name='aviary',
            name='number',
        ),
    ]
