# Generated by Django 5.0.6 on 2024-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0005_company_alter_partner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
