# Generated by Django 5.0.4 on 2024-09-27 23:36

import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0013_animal_name_lower_alter_animal_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 27))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 9, 27))], verbose_name='Дата поступления'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
