# Generated by Django 5.0.4 on 2024-09-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0016_vacancy_salary_alter_animal_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
    ]
