# Generated by Django 5.0.4 on 2024-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0017_remove_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
