# Generated by Django 5.0.4 on 2024-10-26 17:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoopark', '0025_company_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.BooleanField(default=True, verbose_name='Циклическая прокрутка')),
                ('navs', models.BooleanField(default=True, verbose_name='Стрелочки')),
                ('pags', models.BooleanField(default=True, verbose_name='Пагинация')),
                ('auto', models.BooleanField(default=True, verbose_name='Автоматическое переключение')),
                ('stopMouseHover', models.BooleanField(default=True, verbose_name='Остановка мышью')),
                ('delay', models.PositiveIntegerField(default=5000, verbose_name='Задержка')),
            ],
            options={
                'verbose_name': 'Опция слайдера',
                'verbose_name_plural': 'Опции слайдера',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 26))], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_receipt',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 26))], verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 26), verbose_name='Дата'),
        ),
    ]
