# Generated by Django 5.0.6 on 2024-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='images/avatar.jpg', upload_to='images/', verbose_name='Фото'),
        ),
    ]
