# Generated by Django 5.0.6 on 2024-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='images/zoopark_icon.jpg', upload_to='images/', verbose_name='Фото'),
        ),
    ]
