# Generated by Django 5.0.6 on 2024-09-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
